#ifndef KERNEL_X86_ISR_H
#define KERNEL_X86_ISR_H

#include "idt.h"

extern void (*isrs[256])();

/* sadly, x86 doesn't give us our interrupt number, so we need to push it ourselves.
   This means having many stub functions, for which this is a template. The stubs
   themselves are generated by make_isrs.sh. */
#define ISR(num, errcode) \
	extern void isr ## num () ; \
	__asm__ ( \
		".globl isr" #num "\n" \
		"isr" #num ":\n\t" \
			 errcode \
			"pushl $" #num "\n\t" \
			"jmp isr_stub\n\t");

#define DUMMY_ERR "pushl $0\n\t"
#define REAL_ERR

#endif
