
cat << "EOF"
/* This file was generated by make_isrs.sh; do not modify it manually. */
#include <kernel/x86/isr.h>
EOF

i=0
while [ $i -lt 256 ]; do
	case $i in
		8|10|11|12|13|14)
			err=REAL_ERR
			;;
		*)
			err=DUMMY_ERR
			;;
	esac
	printf 'ISR(%d, %s)\n' "$i" "$err"
	i=$(( $i + 1 ))
done

printf 'void (*isrs[])() = {\n'
i=0
while [ $i -lt 255 ]; do
	printf '\tisr%d,\n' $i
	i=$(( $i + 1 ))
done
printf '\tisr255\n'
printf '};\n'
