
cat << "EOF"
/* This file was generated by make_isrs.sh; do not modify it manually. */
#include <kernel/x86/isr.h>
EOF

for i in `seq 0 255`; do
	case $i in
		8|10|11|12|13|14)
			err=REAL_ERR
			;;
		*)
			err=DUMMY_ERR
			;;
	esac
	printf 'ISR(%d, %s)\n' "$i" "$err"
done

printf 'void (*isrs[])() = {\n'
for i in `seq 0 254`; do
	printf '\tisr%d,\n' $i
done
printf '\tisr255\n'
printf '};\n'
